on:
 push:
  paths:
    - project*.toml
    - .github/workflows/forms.yml
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: 
          - de
          - en
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Upload project TOML file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: _callerproject.toml
          path: project_*.toml
          overwrite: true
          if-no-files-found: error
      - name: Generate Forms
        uses: s-ccs/consentform_gh_action@main
        with:
         language: ${{ matrix.language }}
